spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lolsearcherStatics?rewriteBatchedStatements=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: lsk940705
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: embedded
      comment-prefix: '#'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
